<?php

return [

    'commands' => [

        [

            /**
             * The name of the command to respond to.
             */
            'name' => env('SLACK_SLASH_COMMAND_NAME'),

            /**
             * The url to which Slack will send Slack commands.
             */
            'url' => env('SLACK_SLASH_COMMAND_URL'),

            /**
             * The token generated by Slack with which to verify if a incoming slash command request is valid.
             */
            'verification_token' => env('SLACK_SLASH_COMMAND_VERIFICATION_TOKEN'),

            /**
             * The handlers that should process the slash command.
             */
            'handlers' => [
                Spatie\SlashCommand\SlashCommandHandler\CatchAll::class
            ],
        ],
    ],

];