<?php

return [
    /**
     * The URL to request when the slash command is run.
     */
    'slash_command_url' => '',


    /**
     * The token generated by Slack with which to verify if a incoming slash command request is valid.
     */
    'verification_token' => '',

    'slash_command_handlers' => [
        CatchAl
    ]
];