<?php

return [
    /**
     * The URL to request when the slash command is run.
     */
    'slash_command_url' => '',


    /**
     * The token generated by Slack with which to verify if a incoming slash command request is valid.
     */
    'verification_token' => '',

    /**
     * The handlers that should process the slash command.
     */
    'slash_command_handlers' => [
        Spatie\LaravelSlack\SlashCommandHandler\CatchAll::class
    ]
];